
INSERT INTO `customer`(`first_name`, `last_name`, `email`, `password`, `active`, `address`) VALUES ("Patricio", "Estrella", "estrella@gmail.com","$2a$10$GiM8V8HUTvTOPoP0WknXuORPXyrZwWkrpPaKfNFoQNxUSMRtnGBQa", 0, "Fondo de Vikini n.2");
INSERT INTO `customer`(`first_name`, `last_name`, `email`, `password`, `active`, `address`) VALUES ("Bob", "Esponja", "bob@gmail.com","$2a$10$c9XlDP5liTxCLDpfUQ7I0eNNGlQkbkOiy747KaaYP.krKVS4r4ey6", 1, "Fondo de Vikini n.1");
INSERT INTO `customer`(`first_name`, `last_name`, `email`, `password`, `active`, `address`) VALUES ("Arenita", "Mejillas", "arenita@gmail.com","$2a$10$GiM8V8HUTvTOPoP0WknXuORPXyrZwWkrpPaKfNFoQNxUSMRtnGBQa", 1, "Fondo de Vikini n. 8");
INSERT INTO `customer`(`first_name`, `last_name`, `email`, `password`, `active`, `address`) VALUES ("Calamardo", "Tentáculos", "calamardo@gmail.com","$2a$10$GiM8V8HUTvTOPoP0WknXuORPXyrZwWkrpPaKfNFoQNxUSMRtnGBQa", 0, "Fondo de Vikini n.3");
INSERT INTO `customer`(`first_name`, `last_name`, `email`, `password`, `active`, `address`) VALUES ("Selena","Gómez", "gomez@gmail.com","$2a$10$GiM8V8HUTvTOPoP0WknXuORPXyrZwWkrpPaKfNFoQNxUSMRtnGBQa", 1, "Valle de San Fernando de Los Ángeles n.56");
INSERT INTO `customer`(`first_name`, `last_name`, `email`, `password`, `active`, `address`) VALUES ("Benito", "Bodoque", "bodoque@gmail.com","$2a$10$GiM8V8HUTvTOPoP0WknXuORPXyrZwWkrpPaKfNFoQNxUSMRtnGBQa", 1, "Hogan's Alley.  Manhattan");
INSERT INTO `customer`(`first_name`, `last_name`, `email`, `password`, `active`, `address`) VALUES ("Edna", "Krabappel", "edna@gmail.com","$2a$10$GiM8V8HUTvTOPoP0WknXuORPXyrZwWkrpPaKfNFoQNxUSMRtnGBQa", 1, " Evergreen Terrace 82");
INSERT INTO `customer`(`first_name`, `last_name`, `email`, `password`, `active`, `address`) VALUES ("Cristiano", "Ronaldo", "siu@gmail.com","$2a$10$GiM8V8HUTvTOPoP0WknXuORPXyrZwWkrpPaKfNFoQNxUSMRtnGBQa", 0, "Pozuelo de Alarcón");
INSERT INTO `customer`(`first_name`, `last_name`, `email`, `password`, `active`, `address`) VALUES ("Edna", "Moda", "moda@gmail.com","$2a$10$GiM8V8HUTvTOPoP0WknXuORPXyrZwWkrpPaKfNFoQNxUSMRtnGBQa", 1, "Metroville n.100");
INSERT INTO `customer`(`first_name`, `last_name`, `email`, `password`, `active`, `address`) VALUES ("Espergencia", "Valdés", "chilindrina@gmail.com","$2a$10$GiM8V8HUTvTOPoP0WknXuORPXyrZwWkrpPaKfNFoQNxUSMRtnGBQa", 1, "La vecindad n.72");